language: ruby
before_install: gem install bundler
bundler_args: --without guard
script: "bundle exec rspec"
rvm:
  - 2.0.0
notifications:
  email:
    recipients:
      - mathieul@gmail.com
    on_success: change
    on_failure: change
